---
actions:
    - ".github/**"
devcontainer:
    - ".devcontainer/**"
config:
    - ".*"
    - "*.js"
    - "*.json"
    - "*.toml"
    - "*.yaml"
    - "*.yml"
docs:
    - "**.md"
    - "docs/**"
    - LICENSE
source:
    - "src/**"
tests:
    - "tests/**"
dependencies:
    - "*.lock"
