---
name: "Test Dev Container"

on:
    workflow_dispatch:
    pull_request:
        types: [opened, reopened]
        paths:
            - ".devcontainer/*"
            - ".devcontainer/**/*"
    push:
        paths:
            - ".devcontainer/*"
            - ".devcontainer/**/*"

jobs:
    test-dev-container:
        runs-on: ubuntu-latest

        steps:
            - uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
              with:
                  egress-policy: audit

            - name: Checkout
              uses: actions/checkout@v3

            - name: Build and run dev container task
              uses: devcontainers/ci@v0.2
              with:
                  runCmd: |
                      poe lint
                      poe test
